/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isoccerGUI;
import java.util.*;
import isoccer.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Neto
 */
public class iSoccerGUI extends javax.swing.JFrame {
        public ArrayList<Functionary> functionarys;
        public ArrayList<VIP> vips;
        public ArrayList<Bus> buses;
        public ArrayList<Stadium> stadiums;
        public ArrayList<TrainingCenter> centers;
    /**
     * Creates new form iSoccerGUI
     */
    public iSoccerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jButton1.setText("Add Funcionário");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add Sócio Torcedor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add Recurso");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Verificar Recurso");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Edit Sócio Torcedor");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Usar Recurso");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Sair");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Remover Funcionário");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ônibus", "Estádio", "Centro de Treinamento" }));

        jLabel1.setText("Tipo de Recurso");

        jButton9.setText("Relatório");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionários", "Recursos", "Sócio torcedores", "Tudo" }));

        jLabel2.setText("Fazer Relatório de :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addComponent(jButton9)
                .addGap(31, 31, 31)
                .addComponent(jButton7)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FunctionaryGUI fg = new FunctionaryGUI();
        fg.functionarys = this.functionarys;
        fg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VIPGUI vg = new VIPGUI();
        vg.vips = vips;
        vg.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed
    private int ind(String nome) {
        for(int i = 0 ; i < functionarys.size();i++) {
            if(functionarys.get(i).getEmail().equals(nome))
                return i;
        }
        return -1;
    }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String nome = javax.swing.JOptionPane.showInputDialog("Email :");
        if(ISoccer.search(functionarys,nome)) {
            int index = ind(nome);
            functionarys.remove(index);
        } else {
            JOptionPane.showMessageDialog(null,"Este funcionário não está cadastrado");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed
    private int sr(String mail) {
        for(int i = 0 ; i < vips.size();i++) {
            if(vips.get(i).getEmail().equals(mail)) {
                return i;
            }
        }
        return -1;
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String mail = JOptionPane.showInputDialog("Email");
        if(ISoccer.searchVIP(vips,mail)){
            int ind = sr(mail);
            VIP t = vips.get(ind);
            EditVIPGUI temp = new EditVIPGUI();
            temp.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null,"Este email não é de um sócio torcedor");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String tipo = (String) jComboBox1.getSelectedItem();
        try {
            switch (tipo) {
                case "Ônibus":
                    buses.add(new Bus(true));
                    break;
                case "Estádio":
                    int bath = Integer.parseInt(JOptionPane.showInputDialog("Número de Banheiros do estádio"));
                    int sits = Integer.parseInt(JOptionPane.showInputDialog("Número de assentos disponíveis"));
                    int launch = Integer.parseInt(JOptionPane.showInputDialog("Número de lanchonetes Disponíveis no estádio"));
                    this.stadiums.add(new Stadium(true,bath,sits,launch));
                    break;
                default:
                    break;
            }
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "o número digitado é inválido(use um número inteiro)");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String dec = (String) jComboBox1.getSelectedItem();
        int ind;
            switch (dec) {
                case "Ônibus":
                    ind = Bus.containsFree(buses);
                    break;
                case "Estádio":
                    ind = Stadium.containsFree(stadiums);
                    break;
                default:
                    ind = TrainingCenter.containsFree(centers);
                    break;
            }
if(ind !=-1) {
            JOptionPane.showMessageDialog(null,"Número do " + dec + " disponível "+ ind);
        } else {
            JOptionPane.showMessageDialog(null,"Não há nenhum "+ dec +" disponível");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
        String dec = (String) jComboBox1.getSelectedItem();
        int ind = Integer.parseInt( JOptionPane.showInputDialog("Informe o número do " + dec + " disponível"));
        if(ind>=0) {
            if(dec.equals("Ônibus")) {
                if(ind<buses.size()) {
                    (buses.get(ind)).setAvailable(false);
                } else {
                    JOptionPane.showMessageDialog(null,"Não existem "+ind+" Ônibus");
                }
            } else if(dec.equals("Estádio")) {
                if(ind<stadiums.size()) {
                    stadiums.get(ind).setAvailable(false);
                } else {
                    JOptionPane.showMessageDialog(null,"Não existem "+ind+" Estádios");
                }
            } else {
                if(ind<centers.size()) {
                    centers.get(ind).setAvailable(false);
                }else {
                    JOptionPane.showMessageDialog(null,"Não existem "+ind+" Centros de treinamento");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null,ind +" Não é um número natural");
        }
        }catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"Tente usar um número natural");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
    private String printFunc(String s) {
        
            int t = functionarys.size();
            for(int i = 0 ; i < t ; i ++) {
                if(functionarys.get(i).getClasse().equals("Técnico")) {
                    s = s + functionarys.get(i).toString() + "\n";
                }
            }
            for(int i = 0 ; i < t ; i ++) {
                if(functionarys.get(i).getClass().equals(Player.class)) {
                    s = s + functionarys.get(i).toString() + "\n";
                }
            }
            for(int i = 0 ; i < t;i++) {
                if(!functionarys.get(i).getClass().equals(Player.class)&&!functionarys.get(i).getClasse().equals("Técnico")) {
                    s = s + functionarys.get(i).toString()+"\n";
                }
            }
            return s;
    }
    private String printResources(String s) {
        for(int i = 0 ; i < buses.size();i++) {
            s = s + "Ônibus "+Integer.toString(i)+" "+ buses.get(i).toString()+"\n";
        }
        for(int i = 0 ; i < this.stadiums.size();i++) {
            s = s + "Estádio "+Integer.toString(i) + " "+stadiums.get(i).toString()+"\n" ;
        }
        for(int i = 0 ; i < centers.size();i++) {
            s = s+"Centro de treinamento "+Integer.toString(i)+" "+ centers.get(i).toString() +"\n";
        }
        return s;
    }
    private String printSocios (String s) {
        for(int i = 0 ; i < vips.size();i++) {
            s = s +vips.get(i).toString()+"\n";
        }
        return s;
    }
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String dec = (String) jComboBox2.getSelectedItem();
        if(dec.equals("Funcionários")) {
            String s = "";
            s = printFunc(s);
            JOptionPane.showMessageDialog(null,s);
        } else if(dec.equals("Recursos")) {
            String s ="";
            s = printResources(s);
            JOptionPane.showMessageDialog(null,s);
        } else if(dec.equals("Sócio Torcedores")) {
            String s = "";
            s = printSocios(s);
            JOptionPane.showMessageDialog(null,s);
        } else {
            //all
            String s = "",st="",str="";
            String temp = printFunc(s)+printResources(st)+printSocios(str);
            JOptionPane.showMessageDialog(null,temp);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iSoccerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iSoccerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iSoccerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iSoccerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iSoccerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
